spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/shoedb
  web:
    resources:
      static-locations: classpath:/static/, file:frontend/

app:
  jwt:
    secret: "ChangeThisToALongRandomSecretKey_ReplaceInProd"
    expirationMs: 86400000

server:
  port: 8081
